import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';

interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
}

interface QuizProps {
  courseId: string;
  onComplete: (score: number) => void;
}

const Quiz: React.FC<QuizProps> = ({ courseId, onComplete }) => {
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [score, setScore] = useState(0);
  const [showResults, setShowResults] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // TODO: Implement AI-based question generation
    const generateQuestions = async () => {
      try {
        // This is a placeholder. In production, questions would be generated by AI
        const generatedQuestions: Question[] = [
          {
            id: '1',
            question: 'What is compound interest?',
            options: [
              'Interest calculated on initial principal only',
              'Interest calculated on accumulated interest',
              'A fixed interest rate',
              'Simple interest over time'
            ],
            correctAnswer: 'Interest calculated on accumulated interest'
          },
          // Add more questions...
        ];
        setQuestions(generatedQuestions);
        setLoading(false);
      } catch (error) {
        console.error('Error generating questions:', error);
        setLoading(false);
      }
    };

    generateQuestions();
  }, [courseId]);

  const handleAnswer = (selectedAnswer: string) => {
    const correct = selectedAnswer === questions[currentQuestion].correctAnswer;
    if (correct) {
      setScore(score + 1);
    }

    if (currentQuestion + 1 < questions.length) {
      setCurrentQuestion(currentQuestion + 1);
    } else {
      setShowResults(true);
      onComplete(score);
    }
  };

  if (loading) {
    return <div className="text-center p-8">Loading quiz questions...</div>;
  }

  if (showResults) {
    const percentage = (score / questions.length) * 100;
    const passed = percentage >= 70;

    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="text-center p-8"
      >
        <h2 className="text-2xl font-bold mb-4">Quiz Results</h2>
        <p className="text-xl mb-4">
          Your score: {score} out of {questions.length} ({percentage.toFixed(1)}%)
        </p>
        {passed ? (
          <div className="text-green-600">
            Congratulations! You've passed the quiz and earned your certificate!
          </div>
        ) : (
          <div className="text-red-600">
            You need 70% to pass. Please review the material and try again.
          </div>
        )}
      </motion.div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto p-6">
      <div className="mb-4 text-sm text-gray-500">
        Question {currentQuestion + 1} of {questions.length}
      </div>
      
      <motion.div
        key={currentQuestion}
        initial={{ x: 50, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        className="bg-white rounded-lg shadow-lg p-6"
      >
        <h3 className="text-xl font-semibold mb-4">
          {questions[currentQuestion].question}
        </h3>
        
        <div className="space-y-3">
          {questions[currentQuestion].options.map((option, index) => (
            <button
              key={index}
              className="w-full text-left p-3 rounded-lg border hover:bg-blue-50 transition-colors"
              onClick={() => handleAnswer(option)}
            >
              {option}
            </button>
          ))}
        </div>
      </motion.div>
    </div>
  );
};

export default Quiz;
